
version: 2
updates:
  # Maintain dependencies for GitHub Actions - main
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
  # Maintain dependencies for GitHub Actions - notebook-env
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "notebook-env"
    schedule:
      interval: "monthly"
  # Maintain dependencies for pip - main branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
  # Maintain dependencies for pip - notebook-env branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "notebook-env"
    schedule:
      interval: "monthly"
