
version: 2
updates:
  # Maintain dependencies for GitHub Actions - main branch
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Europe/London"
  # Maintain dependencies for GitHub Actions - notebook-env branch
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "notebook-env"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Europe/London"
  # Maintain dependencies for pip - main branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Europe/London"
  # Maintain dependencies for pip - notebook-env branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "notebook-env"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Europe/London"
