
version: 2
updates:
  # Maintain dependencies for GitHub Actions - main
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    groups:
      actions-main:
        patterns:
          - "*"
  # Maintain dependencies for GitHub Actions - notebook-env
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "notebook-env"
    schedule:
      interval: "monthly"
    groups:
      actions-notebook-env:
        patterns:
          - "*"
