
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "dweekly"
  # Maintain dependencies for pip - main branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  # Maintain dependencies for pip - notebook-env branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "notebook-env"
    schedule:
      interval: "weekly"
