repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.3
  hooks:
  - id: nbqa-pyupgrade
    args: ["--py36-plus"]
  - id: nbqa-black
  - id: nbqa-flake8
  - id: nbqa-isort
    args: ["--profile=black"]
