name: Notebook Actions

on:
  pull_request:
    types:
      - opened
    paths:
      - "**.ipynb"
      - "**.csv"

jobs:
  create-binder-badge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Comment on PR with Binder link
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var PR_HEAD_USERREPO = process.env.PR_HEAD_USERREPO;
            var PR_HEAD_REF = process.env.PR_HEAD_REF;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${PR_HEAD_USERREPO}/${PR_HEAD_REF}?urlpath=%2Fvoila%2Frender%2Fvisualise.ipynb) :point_left: Launch a binder notebook on branch _${PR_HEAD_USERREPO}/${PR_HEAD_REF}_`
            })
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_HEAD_USERREPO: ${{ github.event.pull_request.head.repo.full_name }}

  clean-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.5
      - name: Check notebook outputs and metadata
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
