name: Update GitHub Activity

on:
  workflow_dispatch:
  schedule:
    # Run at 00:00 UTC MON-FRI
    - cron: "0 0 * * 1-5"

jobs:
  update-github-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run script to fetch data
        run: |
          python get-data.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Add and Commit updated CSV file
        uses: EndBug/add-and-commit@v9
        with:
          add: github-activity.csv
          message: "Update the GitHub Activity CSV file"
