name: Update GitHub Activity

on:
  workflow_dispatch: []
  schedule:
    # Run at 00:00 UTC MON-FRI
    - cron: "0 0 * * 1-5"

jobs:
  update-github-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.5
      - name: Install Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
      - name: Run script to fetch data
        run: |
          python get-data.py
      - name: Add and Commit updated CSV file
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: github_activity.csv
          message: "Update the GitHub Activity CSV file"
